# -*- coding: utf-8 -*-
"""task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OxfvZGmO2eINGN_sqPEBT6LtZUSEOgH
"""

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model, Model
from tensorflow.keras.preprocessing import image
import cv2

"""##Step 1: Load the model"""

model = load_model("/content/Age_Sex_Detection.keras")
model.summary()

"""##Step 2: Load and preprocess an image"""

def load_and_preprocess_image(img_path, target_size):
    img = image.load_img(img_path, target_size=target_size)
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0  # Normalize if model trained on normalized images
    return img_array, img

"""##Step 3: Create a sub-model to extract activations from intermediate layers
# Choose only convolutional layers
"""

img_path = "/content/IMG-20241202-WA0023.jpg"  # Provide your test image here
img_array, original_img = load_and_preprocess_image(img_path, model.input_shape[1:4])

"""##Step 4: Get activations"""

activations = activation_model.predict(img_array)

"""##Step 5: Visualize activation maps from a few layers"""

layer_names = [layer.name for layer in model.layers if 'conv' in layer.name or 'Conv' in layer.__class__.__name__]

"""### Show activation maps from first few conv layers"""

for layer_name, activation in zip(layer_names, activations[:4]):  # change range for more/fewer layers
    num_filters = min(8, activation.shape[-1])  # visualize max 8 filters
    size = activation.shape[1]

    display_grid = np.zeros((size, size * num_filters))
    for i in range(num_filters):
        x = activation[0, :, :, i]
        x -= x.mean()
        x /= (x.std() + 1e-5)
        x *= 64
        x += 128
        x = np.clip(x, 0, 255).astype('uint8')
        display_grid[:, i * size : (i + 1) * size] = x

    scale = 1. / size
    plt.figure(figsize=(scale * display_grid.shape[1], scale * display_grid.shape[0]))
    plt.title(f'Activations from layer: {layer_name}')
    plt.grid(False)
    plt.imshow(display_grid, aspect='auto', cmap='viridis')
    plt.axis('off')
    plt.show()